#!/usr/bin/env python3
#
# Validate that all IRIs are in namespaces defined in the header

import re
import sys

from argparse import ArgumentParser, FileType


def main():
    p = ArgumentParser()
    p.add_argument('obi', type=FileType('r'))
    p.add_argument('output', type=str)
    args = p.parse_args()

    obi = args.obi
    namespaces = []

    next(obi)
    line = next(obi)
    # Parse the prefixes
    while "owl:Ontology" not in line:
        namespaces.append(line.split('=')[1].split('"')[1])
        line = next(obi)

    invalid = []
    for line in obi:
        if 'Generated by the OWL API' in line:
            # Ignore the generated line
            continue
        if line.strip().startswith('<!--'):
            # Extract IRIs
            has_iri = re.search(r'<!-- (.+) -->', line)
            if has_iri:
                iri = has_iri.group(1)
                ok = False
                for ns in namespaces:
                    if iri.startswith(ns):
                        ok = True
                if not ok:
                    invalid.append(iri)
    obi.close()

    output = args.output
    with open(output, 'w') as f:
        for i in invalid:
            f.write(i + '\n')

    if invalid:
        print('ERROR - {0} invalid IRIs found! See {1} for details.'.format(
            len(invalid), output))
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
