# 'device' should have no asserted children in obi-edit.owl

PREFIX obo:  <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s WHERE {
	?s rdfs:subClassOf* obo:OBI_0000968 ;
	   rdfs:label ?label .
	FILTER (str(?s) != "http://purl.obolibrary.org/obo/OBI_0000968")
}