# 'organization' should have no asserted instances in obi-edit.owl

PREFIX obo:  <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s WHERE {
	?s a obo:OBI_0000835 ;
	   rdfs:label ?label .
	FILTER (str(?s) != "http://purl.obolibrary.org/obo/OBI_0000835")
}